class WaveShareGPS:
    NAME = 'SIM7600X'

    DEFAULT_DEVICE = '/dev/ttyS0'
    POWER_PIN = 4

    POWER_ON_CMD = 'AT+CGNSPWR=1'
    POWER_ON_CMD_RESPONSE = 'OK'
    POWER_OFF_CMD = 'AT+CGNSPWR=0'
    POWER_OFF_CMD_RESPONSE = 'OK'

    DATA_TRANSFER_ON_CMD = 'AT+CGNSTST=1'
    DATA_TRANSFER_ON_CMD_RESPONSE = 'OK'
    DATA_TRANSFER_OFF_CMD = 'AT+CGNSTST=0'
    DATA_TRANSFER_OFF_CMD_RESPONSE = 'OK'

    GPS_INFORMATION_CMD = 'AT+CGNSINF'
    GPS_INFORMATION_CMD_RESPONSE = '+CGNSINF: '
